# Generated by Django 5.2.14 on 2026-05-11 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        ('pdf_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('CSV', 'CSV'), ('XLSX', 'XLSX')], default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='meetings.meeting')),
            ],
            options={
                'db_table': 'email_recipients',
                'unique_together': {('meeting', 'email')},
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('pdf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='pdf_generator.generatedpdf')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.emailrecipient')),
            ],
            options={
                'db_table': 'email_logs',
            },
        ),
    ]
