# Generated by Django 6.0.5 on 2026-05-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_alter_meeting_duration_alter_meeting_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='ai_insights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='key_decisions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
