# Generated by Django 6.0.5 on 2026-05-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meeting_ai_insights_meeting_key_decisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
