# Generated by Django 6.0.5 on 2026-05-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_participant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
