# Generated by Django 6.0.5 on 2026-05-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_alter_task_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratedIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(default='Medium', max_length=10)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('key_decisions', models.TextField(blank=True, null=True)),
                ('tasks_json', models.JSONField(default=list)),
                ('participants_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
