# Generated by Django 6.0.5 on 2026-05-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_integratedintelligence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integratedintelligence',
            name='category',
        ),
        migrations.RemoveField(
            model_name='integratedintelligence',
            name='key_decisions',
        ),
        migrations.RemoveField(
            model_name='integratedintelligence',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='integratedintelligence',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='integratedintelligence',
            name='title',
        ),
        migrations.AddField(
            model_name='integratedintelligence',
            name='deadlines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integratedintelligence',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integratedintelligence',
            name='meeting_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integratedintelligence',
            name='person_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='integratedintelligence',
            name='person_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='integratedintelligence',
            name='person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integratedintelligence',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='integratedintelligence',
            name='tasks_assigned',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integratedintelligence',
            name='meeting_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='integratedintelligence',
            name='participants_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='integratedintelligence',
            name='tasks_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
