# Generated by Django 5.2.14 on 2026-05-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_summary', models.TextField(blank=True)),
                ('overall_sentiment', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_analysis',
            },
        ),
        migrations.CreateModel(
            name='PersonalizedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('task_description', models.TextField()),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('deadline', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'personalized_tasks',
            },
        ),
        migrations.CreateModel(
            name='RoleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('summary_content', models.TextField()),
            ],
            options={
                'db_table': 'role_summaries',
            },
        ),
    ]
