# Generated by Django 5.2.14 on 2026-05-11 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_processing', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='personalizedtask',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_tasks', to='ai_processing.aianalysis'),
        ),
        migrations.AddField(
            model_name='rolesummary',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_summaries', to='ai_processing.aianalysis'),
        ),
    ]
