# Generated by Django 5.2.14 on 2026-05-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_processing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizedtask',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
