# Generated by Django 6.0.5 on 2026-05-11 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=100, unique=True)),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('shared_to_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(max_length=100, unique=True)),
                ('meeting_title', models.CharField(max_length=255)),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('meeting_context', models.TextField()),
                ('ai_summary', models.TextField(blank=True)),
                ('role_based_summary', models.TextField(blank=True)),
                ('custom_summary', models.TextField(blank=True)),
                ('participants_count', models.IntegerField()),
                ('docs_generated', models.IntegerField()),
                ('file_type', models.CharField(max_length=10)),
                ('uploaded_by', models.CharField(max_length=100)),
                ('uploaded_by_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=100, unique=True)),
                ('participant_name', models.CharField(max_length=100)),
                ('participant_email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('speaking_time', models.IntegerField(blank=True, null=True)),
                ('summary_sent', models.BooleanField(default=False)),
                ('summary_sent_time', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('task_description', models.TextField()),
                ('assigned_to', models.CharField(max_length=100)),
                ('assigned_email', models.EmailField(max_length=254)),
                ('priority', models.CharField(max_length=10)),
                ('generated_time', models.DateTimeField(auto_now_add=True)),
                ('document_link', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meeting')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='document',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meeting'),
        ),
    ]
