# Generated by Django 5.2.14 on 2026-05-11 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('pdf_type', models.CharField(choices=[('COMMON', 'Common'), ('PERSONALIZED', 'Personalized')], max_length=20)),
                ('storage_path', models.CharField(blank=True, max_length=1024)),
                ('pdf_url', models.URLField(blank=True, max_length=1024)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='meetings.meeting')),
            ],
            options={
                'db_table': 'generated_pdfs',
            },
        ),
    ]
