# Generated by Django 5.2.14 on 2026-05-12 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('meeting_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_meeting',
            },
        ),
        migrations.CreateModel(
            name='APIDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=1024)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='meetings.apimeeting')),
            ],
            options={
                'db_table': 'api_document',
            },
        ),
        migrations.CreateModel(
            name='APIParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.apimeeting')),
            ],
            options={
                'db_table': 'api_participant',
            },
        ),
        migrations.CreateModel(
            name='APITask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField()),
                ('person_name', models.CharField(max_length=255)),
                ('priority', models.CharField(max_length=50)),
                ('deadline', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='meetings.apimeeting')),
            ],
            options={
                'db_table': 'api_task',
            },
        ),
    ]
